FROM node:24

# Install Cypress dependencies
RUN apt-get update -y && \
    apt-get install -y \
    xvfb \
    libgtk-3-0 \
    libnss3 \
    libasound2 \
    libxss1 \
    libxtst6 \
    libgbm-dev \
    wget \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /react

COPY package*.json ./

RUN npm install

RUN chown -R $USER:$USER /react

EXPOSE 5173

CMD ["npm", "run", "dev"]

#CMD ["sh"]

# npx @tailwindcss/cli ???
# npm install -D tailwindcss
# npx shadcn@latest init --base-color neutral --yes
# npx shadcn-ui@latest add card
# npm install -D @rollup/plugin-alias
# npx tsc --init
# RUN npx shadcn@latest init
# RUN npm install tailwindcss @tailwindcss/vite
# npm install -D tailwindcss postcss autoprefixer
# npx tailwindcss init -p
# npm install tailwindcss @tailwindcss/cli
# npx shadcn@latest add card

# npm install --save-dev vitest @testing-library/react @testing-library/jest-dom @testing-library/user-event jsdom @vitejs/plugin-react @types/jest

# npm install cypress --save-dev
# npm install @types/cypress --save-dev
# npx cypress open
# npx cypress run
# npx cypress run --browser chrome --headed


# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts"
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true
# npx cypress run --browser chrome --headed --spec "cypress/e2e/countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit,retries=2
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit,retries=2,screenshotOnRunFailure=false
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit,retries=2,screenshotOnRunFailure=false,no-exit
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit,retries=2,screenshotOnRunFailure=false,no-exit,no-colors
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit,retries=2,screenshotOnRunFailure=false,no-exit,no-colors,no-exit
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit,retries=2,screenshotOnRunFailure=false,no-exit,no-colors,no-exit,no-colors
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit,retries=2,screenshotOnRunFailure=false,no-exit,no-colors,no-exit,no-colors,no-exit
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit,retries=2,screenshotOnRunFailure=false,no-exit,no-colors,no-exit,no-colors,no-exit,no-colors
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit,retries=2,screenshotOnRunFailure=false,no-exit,no-colors,no-exit,no-colors,no-exit,no-colors,no-exit
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit,retries=2,screenshotOnRunFailure=false,no-exit,no-colors,no-exit,no-colors,no-exit,no-colors,no-exit,no-colors
# npx cypress run --browser chrome --headed --spec "cypress/e2e /countries.cy.ts" --config video=false,viewportWidth=1280,viewportHeight=720,baseUrl=http://localhost:5173 --headed --record --key your-record-key --parallel --ci-build-id your-build-id --group your-group-name --no-exit --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true,quiet=true,timestamp=false,charts=false,reportFilename=custom-report,inlineAssets=true,attachScreenshots=true,codeCoverage=true,sendAllRequests=true,customConfigFile=cypress.json,env=your-env,debug=true,verbose=true,silent=true,noColors=true,forceExit=true,retries=2,screenshotOnRunFailure=false,video=false,browser=chrome,no-exit,retries=2,screenshotOnRunFailure=false,no-exit,no-colors,no-exit,no-colors,no-exit,no-colors,no-exit,no-colors,no-exit
